### PR TITLE
Fix FormattedMessage so it works with children

### PR DESCRIPTION
**Pull request by enterline**
Fix FormattedMessage so it works with children so we can do something like this:

``` javascript
<FormattedMessage
            id="greeting.welcome_message"
            defaultMessage={`
                Welcome {name}, you have received {unreadCount, plural,
                    =0 {no new messages}
                    one {{formattedUnreadCount} new message}
                    other {{formattedUnreadCount} new messages}
                } since {formattedLastLoginTime}.
            `}
            values={{
                name: {name},
                unreadCount: unreadCount,
                formattedUnreadCount: (
                    <FormattedNumber value={unreadCount} />
                ),
                formattedLastLoginTime: (
                    <FormattedRelative
                        value={lastLoginTime}
                        updateInterval={1000}
                    />
                ),
            }}
        />
```

like this example: https://github.com/yahoo/react-intl/blob/master/examples/nested/src/client/components/widgets/greeting.js

### CODE REVIEW

**Comment by frostney** [comment]
Hi @enterline, this looks amazing. Thank you so much 👍 

Quick question before I merge this in: Do we need something similar for `FormattedHTMLMessage` as well?

**Comment by enterline** [comment]
@frostney I have not explored `FormattedHTMLMessage` as per documentation, it recommends not using it: https://github.com/yahoo/react-intl/wiki/Components#formattedhtmlmessage

**Comment by frostney** [comment]
Thank you so much for the explanation and the contribution. 👍

**Comment by frostney** [comment]
This just landed with `2.1.0`

**Pull request merged**
